language: python
python:
    - 2.7  # tox still runs all versions as expected
install: pip install . tox
script: tox
branches:
  only:
    - master
    - /^v\d.*$/  # Build releases, which get tagged e.g. v0.1.dev3
